baseURL: "https://luislf.xyz"
languageCode: en-us
title: Luis López Fernández
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Luis López Fernández
  description: "Personal website of Luis López Fernández"
  keywords: [Artificial Intelligence, AI, Machine Learning, ML, Project Management, Portfolio, Leadership, Engineering]
  author: Luis López Fernández
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark #auto, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "LLF"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Luis López Fernández
    subtitle_1: 🧠Artificial Intelligence, Machine Learning | 🎯Project Management, Leadership
    subtitle_2: 🚀Engineering the Future, Managing Today's Tech
    imageUrl: "/assets/images/profile.png"
    imageWidth: 250
    imageHeight: 250
    imageTitle: profile_image
    buttons:
      - name: About Me
        url: about_me      
      - name: CV
        url: assets/230829_CV_LuisLopezFernandez.pdf
      - name: Contact me
        url: mailto:luislofer89@gmail.com


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog! Here I will collect and summarize a bunch of AI-related topics

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/luislopezfdez"
    - name: github
      url: "https://github.com/luislofer89"
    - name: twitter
      url: "https://twitter.com/luislofer89"
    - name: instagram
      url: "https://www.instagram.com/luisloez89"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: posts
      name: Blog
      url: /posts/
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 20
    - identifier: About me
      name: About me
      url: /about_me
      weight: 30


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
